Repository moving-team/moving-fe, pull requests merged in 2024-12, with the labels that each got.

#21 [이율리] 공통 컴포넌트 - 프로필 카드 구현
  package-lock.json
  package.json
  src/assets/icons/ic_writing_gray.svg
  src/components/card/Card.module.css
  src/components/card/Card.tsx
  src/components/card/DriverCard.module.css
  src/components/card/DriverCard.tsx
  src/components/card/DriverProfile.module.css
  src/components/card/DriverProfile.tsx
  src/components/card/Profile.module.css
  src/components/card/Profile.tsx
  src/lib/function/useMediaQuery.ts
  src/page/driver/costCall/index.module.css
  src/page/driver/costCall/index.tsx
  src/style/globals.css
Labels: 공통

#19 [김민서] 공통 컴포넌트 - 페이지네이션 구현
  src/components/common/Pagination.module.css
  src/components/common/Pagination.tsx
  src/page/user/login/index.tsx
Labels: 공통

#20 [김효인] 견적요청페이지
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  src/assets/icons/ic_check_circle_empty_large.svg
  src/assets/icons/ic_check_circle_empty_medium.svg
  src/assets/icons/ic_check_circle_large.svg
  src/assets/icons/ic_empty_heart_large.svg
  src/assets/icons/ic_empty_heart_medium.svg
  src/assets/icons/ic_full_heart_large.svg
  src/assets/icons/ic_full_heart_medium.svg
  src/assets/icons/ic_search_large.svg
  src/lib/api/kakao.ts
  src/page/user/costCall/MovingAddress.module.css
  src/page/user/costCall/MovingAddress.tsx
  src/page/user/costCall/MovingAddressModal.module.css
  src/page/user/costCall/MovingAddressModal.tsx
  src/page/user/costCall/MovingComments.module.css
  src/page/user/costCall/MovingComments.tsx
  src/page/user/costCall/MovingDate.css
  src/page/user/costCall/MovingDate.tsx
  src/page/user/costCall/MovingType.module.css
  src/page/user/costCall/MovingType.tsx
  src/page/user/costCall/Navigation.module.css
  src/page/user/costCall/Navigation.tsx
  src/page/user/costCall/index.module.css
  src/page/user/costCall/index.tsx
  src/root.tsx
  src/style/globals.css
Labels: 진행중

#30 [김효인] 주소 입력 모달창 페이지네이션 추가, 리액트쿼리 추가
  .vscode/settings.json
  package-lock.json
  package.json
  src/assets/icons/ic_search_medium.svg
  src/components/common/Pagination.tsx
  src/components/pagination/Pagination.module.css
  src/components/pagination/Pagination.tsx
  src/components/review/Review.module.css
  src/components/review/Review.tsx
  src/index.tsx
  src/lib/api/kakao.ts
  src/page/user/costCall/MovingAddressModal.tsx
  src/page/user/costCall/components/MovingAddress.module.css
  src/page/user/costCall/components/MovingAddress.tsx
  src/page/user/costCall/components/MovingAddressModal.module.css
  src/page/user/costCall/components/MovingAddressModal.tsx
  src/page/user/costCall/components/MovingComments.module.css
  src/page/user/costCall/components/MovingComments.tsx
  src/page/user/costCall/components/MovingDate.css
  src/page/user/costCall/components/MovingDate.tsx
  src/page/user/costCall/components/MovingType.module.css
  src/page/user/costCall/components/MovingType.tsx
  src/page/user/costCall/components/Navigation.module.css
  src/page/user/costCall/components/Navigation.tsx
  src/page/user/costCall/index.module.css
  src/page/user/costCall/index.tsx
  src/root.tsx
Labels: 완료

#32 [이율리] 공통 컴포넌트 - 유저 기준 profile 카드 구현
  src/components/card/DriverCard.tsx
  src/components/card/DriverProfile.module.css
  src/components/card/DriverProfile.tsx
  src/components/card/UserCard.module.css
  src/components/card/UserCard.tsx
  src/components/card/UserProfile.module.css
  src/components/card/UserProfile.tsx
  src/lib/function/utils.ts
  src/page/driver/costCall/index.module.css
  src/page/driver/costCall/index.tsx
Labels: 공통

#34 [김효인] 칩 기능 추가
  src/components/chip/Chip.tsx
  src/components/chip/chip.module.css
Labels: 완료

#35 [김효인] 견적요청 반응형웹페이지 수정
  src/page/user/costCall/components/MovingAddress.module.css
  src/page/user/costCall/components/MovingAddressModal.module.css
  src/page/user/costCall/components/MovingComments.module.css
  src/page/user/costCall/components/MovingComments.tsx
  src/page/user/costCall/components/Navigation.module.css
  src/page/user/costCall/index.module.css
Labels: 완료

#31 [박명준] 모달 공통 컴포넌트 추가 및 공통 컴포넌트 반응형 구현
  src/components/btn/Button.module.css
  src/components/modal/ModalContainer.module.css
  src/components/modal/ModalContainer.tsx
  src/components/nocontents/NoContents.module.css
  src/components/nocontents/NoContents.tsx
  src/components/tab/Tab.module.css
  src/page/user/movingReview/components/WritingReview.module.css
  src/page/user/movingReview/components/WritingReview.tsx
  src/page/user/movingReview/index.module.css
  src/page/user/movingReview/index.tsx
Labels: 진행중

#36 [이율리] 공통 컴포넌트 - profile 카드 수정
  src/components/card/DriverCard.module.css
  src/components/card/DriverCard.tsx
  src/components/card/DriverProfile.module.css
  src/components/card/DriverProfile.tsx
  src/components/card/UserCard.module.css
  src/components/card/UserCard.tsx
  src/components/card/UserProfile.tsx
  src/page/driver/costCall/index.module.css
  src/page/driver/costCall/index.tsx
Labels: 공통

#37 [김대건] nav 개발 및 반응형 적용
  src/assets/icons/ic_profile_medium.svg
  src/assets/icons/ic_profile_upload_medium.svg
  src/components/nav/Nav.module.css
  src/components/nav/Nav.tsx
  src/components/nav/NavMenuModal.module.css
  src/components/nav/NavMenuModal.tsx
  src/components/nav/NonLoginNav.module.css
  src/components/nav/NonLoginNav.tsx
  src/components/nav/ProfileModal.module.css
  src/components/nav/ProfileModal.tsx
  src/layout/DriverLayout.tsx
  src/layout/RendingLayout.module.css
  src/layout/RendingLayout.tsx
  src/layout/UserLayout.tsx
  src/lib/function/direction.ts
  src/page/driver/editInfo/index.module.css
  src/page/driver/editProfile/index.module.css
  src/page/user/editInfo/index.module.css
  src/page/user/editProfile/index.module.css
  src/page/user/register/index.module.css
  src/root.tsx
Labels: 공통

#43 [김효인] 달력에 손없는 날 표시
  package-lock.json
  package.json
  src/page/user/costCall/components/MovingDate.css
  src/page/user/costCall/components/MovingDate.tsx
  src/react-app-env.d.ts
Labels: 완료

#48 [김효인] 라이브러리 오류 수정
  src/page/user/receivedCostDetail/components/ReceivedCostInfo.module.css
  src/page/user/receivedCostDetail/components/ReceivedCostInfo.tsx
  src/page/user/receivedCostDetail/index.module.css
  src/page/user/receivedCostDetail/index.tsx
  src/react-app-env.d.ts
  src/root.tsx
  src/types/holiday-kr.d.ts
  tsconfig.json
Labels: 완료

#45 [이율리] 공통 컴포넌트 - 프로필 수정
  src/components/card/DriverCard.tsx
  src/components/card/UserCard.tsx
  src/components/card/UserProfile.module.css
  src/components/card/UserProfile.tsx
  src/components/card/type.ts
  src/page/driver/costCall/components/CallList.tsx
  src/page/driver/costCall/components/mockData.ts
  src/page/driver/costHandler/mockData.ts
  src/page/user/favoriteMover/mockData.ts
Labels: 공통

#52 [김효인] chip 모바일버전 글자 수정
  src/components/chip/Chip.module.css
  src/components/chip/Chip.tsx
Labels: 완료, 공통

#53 [김민서] 기사님 찾기 페이지 - 목데이터 및 기사님 프로필 카드 추가
  src/components/card/DriverCard.module.css
  src/components/card/DriverCard.tsx
  src/page/root/searchDriver/components/DriverSearch.tsx
  src/page/root/searchDriver/index.module.css
  src/page/root/searchDriver/index.tsx
Labels: 완료

#58 [김민서] 백엔드 필드명에 맞춰 목 데이터 및 컴포넌트 수정
  src/components/card/type.ts
  src/components/chip/Chip.tsx
  src/page/driver/costCall/components/mockData.ts
  src/page/driver/costHandler/mockData.ts
  src/page/root/DriverDetailPage.tsx
  src/page/root/searchDriver/index.tsx
  src/page/user/favoriteMover/mockData.ts
  src/page/user/receivedCostDetail/components/ReceivedCostInfo.tsx
  src/page/user/receivedCostDetail/mockData.ts
Labels: bug, 공통

#56 [김효인] 받았던 견적 페이지, 페이지네이션 수정
  src/components/pagination/Pagination.tsx
  src/page/user/costCall/components/MovingAddressModal.tsx
  src/page/user/receivedCost/components/ReceivedCostCard.module.css
  src/page/user/receivedCost/components/ReceivedCostCard.tsx
  src/page/user/receivedCost/index.module.css
  src/page/user/receivedCost/index.tsx
  src/page/user/receivedCost/mock.ts
  src/page/user/receivedCostDetail/components/ReceivedCostInfo.module.css
Labels: 진행중

#61 [박명준] 내가 작성한 리뷰 페이지
  src/components/card/DriverCard.module.css
  src/components/card/UserCard.module.css
  src/components/card/UserProfile.tsx
  src/page/user/favoriteMover/index.module.css
  src/page/user/movingReview/components/MyReview.module.css
  src/page/user/movingReview/components/MyReview.tsx
  src/page/user/movingReview/components/WritableReviews.tsx
  src/page/user/movingReview/components/moverMockData.ts
  src/page/user/movingReview/components/reviewMockData.ts
  src/page/user/movingReview/index.module.css
  src/page/user/movingReview/index.tsx
Labels: 완료

#62 [이율리] 받은 요청 페이지, 공통 컴포넌트 수정
  src/components/card/DriverCard.module.css
  src/components/card/DriverProfile.module.css
  src/components/card/DriverProfile.tsx
  src/components/card/UserCard.tsx
  src/components/card/type.ts
  src/lib/function/utils.ts
  src/page/driver/costCall/components/CallList.module.css
  src/page/driver/costCall/components/CallList.tsx
  src/page/driver/costCall/components/Dropdown.tsx
  src/page/driver/costCall/components/Filter.tsx
  src/page/driver/costCall/components/ModalInput.module.css
  src/page/driver/costCall/components/ModalInput.tsx
  src/page/driver/costCall/components/mockData.ts
  src/page/driver/costCall/index.tsx
  src/page/driver/costHandler/index.tsx
  src/page/driver/costHandler/mockData.ts
Labels: 공통

#63 [김민서] 기사님 상세 페이지 - 리뷰 추가 및 리뷰 컴포넌트 구조 수정 (백엔드 필드명 반영)
  src/components/review/Review.module.css
  src/components/review/Review.tsx
  src/page/root/DriverDetail.module.css
  src/page/root/DriverDetailPage.tsx
Labels: 완료

#64 [박명준] Tab 공통 컴포넌트 기능 추가
  src/components/tab/Tab.tsx
Labels: 완료

#65 [박명준] 견적 정보 공통 컴포넌트 추가 (CostInfo)
  src/components/costInfo/CostInfo.module.css
  src/components/costInfo/CostInfo.tsx
  src/page/user/movingReview/index.module.css
  src/page/user/pendingCost/index.module.css
  src/page/user/pendingCost/index.tsx
Labels: 완료, 공통

#60 [김효인] 받았던 견적 모바일, 알림 추가
  src/components/nav/Nav.tsx
  src/components/nav/NotificationModal.module.css
  src/components/nav/NotificationModal.tsx
  src/components/nav/ProfileModal.module.css
  src/components/nav/mockData.ts
  src/lib/function/direction.ts
  src/lib/function/utils.ts
  src/page/user/costCall/components/CostCallContent.tsx
  src/page/user/costCall/index.tsx
  src/page/user/receivedCost/components/ReceivedCostCard.tsx
  src/page/user/receivedCost/index.tsx
  src/page/user/receivedCostDetail/components/ReceivedCostInfo.module.css
  src/page/user/receivedCostDetail/components/ReceivedList.module.css
  src/page/user/receivedCostDetail/index.module.css
  src/page/user/receivedCostDetail/index.tsx
Labels: 진행중

#66 [박명준] 대기 중인 견적 페이지
  src/page/user/pendingCost/components/PendingList.module.css
  src/page/user/pendingCost/components/PendingList.tsx
  src/page/user/pendingCost/components/mockData.ts
  src/page/user/pendingCost/index.module.css
  src/page/user/pendingCost/index.tsx
Labels: 완료

#69 [이율리] 견적 관리 페이지 기본 레이아웃 구현
  src/components/card/DriverProfile.module.css
  src/components/card/UserProfile.module.css
  src/page/driver/costCall/index.module.css
  src/page/driver/costCall/index.tsx
  src/page/driver/costHandler/index.module.css
  src/page/driver/costHandler/index.tsx
  src/page/driver/costHandler/mockData.ts
  src/root.tsx
Labels: 완료

#70 [김민서] 기사님 상세 페이지 - 데스크탑 화면용 기사님 찜하기 및 지정견적 버튼, 모바일/태블릿 화면용 하단 탭 반응형 스타일 추가
  src/assets/icons/ic_full_heart_small.svg
  src/components/btn/Button.tsx
  src/page/root/searchDriver/DriverDetail.module.css
  src/page/root/searchDriver/DriverDetailPage.tsx
  src/page/root/searchDriver/components/FixedBottomTab.module.css
  src/page/root/searchDriver/components/FixedBottomTab.tsx
  src/root.tsx
Labels: 완료

#71 Hotfix/fix 공통
  src/components/card/DriverCard.tsx
  src/components/card/DriverProfile.module.css
  src/components/card/DriverProfile.tsx
  src/components/card/UserCard.tsx
  src/components/card/UserProfile.tsx
  src/components/card/type.ts
  src/page/driver/costCall/components/CallList.tsx
  src/page/driver/costCall/components/mockData.ts
  src/page/driver/costHandler/index.tsx
  src/page/driver/costHandler/mockData.ts
  src/page/root/searchDriver/DriverDetailPage.tsx
  src/page/root/searchDriver/index.tsx
  src/page/root/searchDriver/mockData.ts
  src/page/user/favoriteMover/index.tsx
  src/page/user/favoriteMover/mockData.ts
  src/page/user/movingReview/components/MyReview.tsx
  src/page/user/movingReview/components/WritableReviews.tsx
  src/page/user/movingReview/components/WritingReview.tsx
  src/page/user/movingReview/components/moverMockData.ts
  src/page/user/movingReview/components/reviewMockData.ts
  src/page/user/pendingCost/components/PendingList.tsx
  src/page/user/receivedCost/components/ReceivedCostCard.tsx
  src/page/user/receivedCost/mock.ts
  src/page/user/receivedCostDetail/components/ReceivedList.tsx
Labels: bug, 진행중, 공통

#72 [박명준] 대기 중인 견적 페이지
  src/components/btn/Button.module.css
  src/components/btn/Button.tsx
  src/components/costInfo/CostInfo.module.css
  src/components/costInfo/CostInfo.tsx
  src/components/modal/ModalContainer.tsx
  src/page/user/pendingCost/components/PendingList.tsx
  src/page/user/pendingCost/components/mockData.ts
  src/page/user/pendingCost/index.module.css
  src/page/user/pendingCost/index.tsx
Labels: 완료

#73 [공통] profile 컴포넌트 수정
  src/components/card/DriverCard.module.css
  src/components/card/DriverCard.tsx
  src/components/card/DriverProfile.module.css
  src/components/card/UserCard.module.css
  src/components/card/UserCard.tsx
  src/components/card/UserProfile.module.css
  src/components/card/UserProfile.tsx
  src/lib/function/utils.ts
Labels: 완료, 공통

#74 [박명준] 기사님 마이 페이지 구현 및 다른 페이지 스타일 수정
  src/components/nav/ProfileModal.tsx
  src/lib/function/direction.ts
  src/page/driver/myPage/index.module.css
  src/page/driver/myPage/index.tsx
  src/page/root/searchDriver/components/DriverSearch.module.css
  src/page/root/searchDriver/index.module.css
  src/page/user/pendingCost/index.module.css
  src/root.tsx
Labels: 완료

#75 [김효인] Nav bar 모달창 수정, 받았던 견적 견적정보 추가
  .vscode/settings.json
  src/components/nav/Nav.module.css
  src/components/nav/Nav.tsx
  src/components/nav/NavMenuModal.module.css
  src/components/nav/NotificationModal.tsx
  src/components/nav/ProfileModal.module.css
  src/components/nav/ProfileModal.tsx
  src/layout/DriverLayout.tsx
  src/layout/RendingLayout.tsx
  src/layout/UserLayout.tsx
  src/lib/function/useMediaQuery.ts
  src/page/user/costCall/components/MovingAddressModal.tsx
  src/page/user/costCall/components/MovingDate.tsx
  src/page/user/receivedCost/components/ReceivedCostCard.module.css
  src/page/user/receivedCost/components/ReceivedCostCard.tsx
  src/page/user/receivedCost/mock.ts
  src/page/user/receivedCostDetail/components/ReceivedCostInfo.module.css
  src/page/user/receivedCostDetail/components/ReceivedCostInfo.tsx
  src/page/user/receivedCostDetail/components/ReceivedList.module.css
  src/page/user/receivedCostDetail/components/ReceivedList.tsx
  src/page/user/receivedCostDetail/index.tsx
  src/page/user/receivedCostDetail/mockData.ts
Labels: 완료, 공통

#77 [이율리] 견적 관리, 견적 상세 페이지
  src/assets/icons/ic_check_large.svg
  src/assets/icons/ic_check_medium.svg
  src/components/card/DriverCard.module.css
  src/components/card/DriverCard.tsx
  src/components/card/UserCard.module.css
  src/components/card/UserCard.tsx
  src/components/card/UserProfile.module.css
  src/components/costInfo/CostInfo.tsx
  src/components/nav/NavMenuModal.module.css
  src/components/snsShare/ShareKakao.tsx
  src/components/snsShare/SnsShare.module.css
  src/components/snsShare/SnsShare.tsx
  src/lib/function/direction.ts
  src/lib/function/useMediaQuery.ts
  src/lib/function/utils.ts
  src/page/driver/costCall/components/CallList.module.css
  src/page/driver/costCall/components/CallList.tsx
  src/page/driver/costCall/components/mockData.ts
  src/page/driver/costCall/index.module.css
  src/page/driver/costCall/index.tsx
  src/page/driver/costCall/mockData.ts
  src/page/driver/costDetail/index.module.css
  src/page/driver/costDetail/index.tsx
  src/page/driver/costDetail/mockData.ts
  src/page/driver/costHandler/index.module.css
  src/page/driver/costHandler/index.tsx
  src/page/driver/costHandler/mockData.ts
  src/root.tsx
Labels: 완료

#76 [김민서] 대기 중인 견적 및 받았던 견적에 대한 견적 상세 페이지
  src/assets/icons/ic_info_large.svg
  src/assets/icons/ic_info_medium.svg
  src/components/btn/Button.module.css
  src/components/btn/Button.tsx
  src/components/card/DriverCard.tsx
  src/components/toast/Toast.module.css
  src/components/toast/Toast.tsx
  src/page/user/costDetail/components/CostDetailBottomTab.module.css
  src/page/user/costDetail/components/CostDetailBottomTab.tsx
  src/page/user/costDetail/index.module.css
  src/page/user/costDetail/index.tsx
  src/page/user/pendingCost/components/PendingList.tsx
  src/page/user/pendingCost/components/mockData.ts
  src/page/user/receivedCostDetail/components/ReceivedList.tsx
  src/page/user/receivedCostDetail/mockData.ts
  src/root.tsx
Labels: 완료

#80 [김민서] 기사님 상세 페이지 및 대기 중인 견적 및 받았던 견적에 대한 견적 상세 페이지 세부 사항 추가
  src/assets/icons/ic_empty_heart_small.svg
  src/assets/icons/ic_full_heart_small.svg
  src/components/btn/Button.module.css
  src/page/root/driverDetail/DriverDetail.module.css
  src/page/root/driverDetail/DriverDetailPage.tsx
  src/page/root/searchDriver/components/FixedBottomTab.tsx
  src/page/root/searchDriver/mockData.ts
  src/page/user/costDetail/components/CostDetailBottomTab.tsx
  src/page/user/costDetail/index.tsx
  src/root.tsx
Labels: 완료

#83 [공통] API 호출 함수 추가 및 리액트 훅 추가
  src/components/card/DriverCard.tsx
  src/components/card/DriverProfile.tsx
  src/components/card/UserCard.tsx
  src/components/card/UserProfile.tsx
  src/lib/api/assignedEstimateReq.ts
  src/lib/api/axios.ts
  src/lib/api/driver.ts
  src/lib/api/estimate.ts
  src/lib/api/estimateReq.ts
  src/lib/api/favorite.ts
  src/lib/api/review.ts
  src/lib/function/utils.ts
  src/lib/useQueries/assignedEstimateReq.ts
  src/lib/useQueries/driver.ts
  src/lib/useQueries/estimate.ts
  src/lib/useQueries/estimateReq.ts
  src/lib/useQueries/favorite.ts
  src/lib/useQueries/notification.ts
  src/lib/useQueries/review.ts
  src/lib/useQueries/user.ts
  src/page/driver/costCall/components/CallList.tsx
  src/page/driver/costCall/mockData.ts
  src/page/driver/costDetail/mockData.ts
  src/page/driver/costHandler/mockData.ts
  src/page/driver/myPage/index.tsx
  src/page/user/movingReview/components/WritingReview.tsx
  src/page/user/movingReview/components/moverMockData.ts
  src/page/user/movingReview/components/reviewMockData.ts
  src/page/user/pendingCost/components/mockData.ts
  src/page/user/receivedCost/mock.ts
  src/types/apiTypes.ts
  src/types/cardTypes.ts
Labels: 공통

#88 [김대건] 소셜 로그인 기능 완성(카카오)
  src/components/nav/Nav.tsx
  src/components/page/auth/AuthBottom.tsx
  src/context/authContext.tsx
Labels: 완료

#90 [김효인] axios interceptors error
  src/lib/api/axios.ts
  src/page/user/receivedCostDetail/components/ReceivedList.module.css
  src/page/user/receivedCostDetail/components/ReceivedList.tsx
  src/page/user/receivedCostDetail/index.tsx
  src/page/user/receivedCostDetail/mockData.ts
Labels: 완료

#91 [이율리] api 연동
  src/components/card/UserCard.tsx
  src/components/costInfo/CostInfo.tsx
  src/components/search/Search.tsx
  src/lib/api/estimate.ts
  src/lib/function/utils.ts
  src/lib/useQueries/estimate.ts
  src/page/driver/costCall/components/CallList.tsx
  src/page/driver/costCall/components/Dropdown.tsx
  src/page/driver/costCall/components/Filter.tsx
  src/page/driver/costCall/components/ModalInput.tsx
  src/page/driver/costCall/index.tsx
  src/page/driver/costDetail/index.tsx
  src/page/driver/costHandler/index.tsx
  src/types/apiTypes.ts
Labels: 완료

#92 [김대건] 새로고침 시 리다이렉션 문제 해결
  src/components/nav/Nav.tsx
  src/components/nav/ProfileModal.tsx
  src/context/authContext.tsx
  src/layout/RendingLayout.tsx
  src/page/driver/login/index.tsx
  src/page/driver/signup/index.tsx
  src/page/user/login/index.tsx
  src/page/user/signup/index.tsx
Labels: 완료

#95 [김민서] api 추가 연동
  src/page/root/driverDetail/DriverDetailPage.tsx
  src/page/user/costDetail/index.tsx
  src/page/user/pendingCost/components/PendingList.tsx
  src/page/user/receivedCostDetail/components/ReceivedList.tsx
  src/page/user/receivedCostDetail/mockData.ts
  src/types/apiTypes.ts
Labels: 완료
